import { OnboardingFormData } from '@/types/onboarding';

// ── Error types ───────────────────────────────────────────────────────────────

export interface ApiValidationIssue {
  field: string;
  message: string;
}

export class ApiValidationError extends Error {
  issues: ApiValidationIssue[];
  constructor(issues: ApiValidationIssue[]) {
    super('Validation failed');
    this.name = 'ApiValidationError';
    this.issues = issues;
  }
}

export class ApiNetworkError extends Error {
  constructor() {
    super('Unable to connect to the server. Please check your connection and try again.');
    this.name = 'ApiNetworkError';
  }
}

export class ApiError extends Error {
  status: number;
  constructor(message: string, status: number) {
    super(message);
    this.name = 'ApiError';
    this.status = status;
  }
}

// ── Result types ──────────────────────────────────────────────────────────────

export interface SubmitOnboardingResult {
  applicationId: string;
  submittedAt: string;
}

export interface UploadResult {
  objectKey: string;
  fileName: string;
  fileSize: number;
  uploadedAt: string;
}

// ── Helpers ───────────────────────────────────────────────────────────────────

function getApiBase(): string {
  return process.env.NEXT_PUBLIC_API_BASE_URL ?? 'http://localhost:8787';
}

function buildPayload(formData: OnboardingFormData): Record<string, unknown> {
  const { personalInfo: p, i9Data, w4Data, employmentReferences, safetyEducation, signatureData, uploadedDocuments: docs } = formData;

  // I-9 fields are now the primary source of personal identity (user edits them directly in the I-9).
  // Fall back to personalInfo for any field not yet set in i9Data.
  const i9p = i9Data;

  return {
    // Top-level fields validated by the Worker schema — prefer i9Data (user may have edited in I-9)
    firstName: i9p.firstName || p.firstName,
    lastName:  i9p.lastName  || p.lastName,
    email:     i9p.email     || p.email,
    phone:     i9p.phone     || p.phone,
    // Supplementary sections — Worker strips unknown keys via Zod
    personalInfo: {
      middleInitial:  i9p.middleInitial  || p.middleInitial,
      otherLastNames: i9p.otherLastNames || p.otherLastNames,
      address:        i9p.address        || p.address,
      aptNumber:      i9p.aptNumber      || p.aptNumber,
      city:           i9p.city           || p.city,
      state:          i9p.state          || p.state,
      zip:            i9p.zip            || p.zip,
      // SSN intentionally omitted from network payload
    },
    // i9SignatureDataUrl is a large base64 PNG — passed here for server-side PDF generation,
    // then stripped from the stored payload_json in D1 by the Worker.
    i9Data,
    // W-4 data — no W-4 PDF is generated by this route today; ssn is sent
    // only so the Worker can redact it before writing applications.payload_json
    // (routes/onboarding.ts), the same treatment i9Data.ssn already gets.
    w4Data,
    employmentReferences,
    safetyEducation,
    signatureData: {
      typedName: signatureData.typedName,
      signedDate: signatureData.signedDate,
      hasSignature: !!(signatureData.signatureDataUrl || signatureData.typedName),
    },
    // Vaccine declination decisions + proof document metadata
    vaccineDeclarations: Object.fromEntries(
      Object.entries(formData.acknowledgements)
        .filter(([, entry]) => entry.decision != null)
        .map(([stepId, entry]) => [stepId, {
          decision:       entry.decision,
          typedSignature: entry.decision === 'declining' ? entry.typedSignature : undefined,
          signedAt:       entry.decision === 'declining' ? entry.signedAt : undefined,
          proofDocument:  entry.decision === 'providing_proof'
            ? (formData.vaccineProofDocuments?.[stepId]
              ? { name: formData.vaccineProofDocuments[stepId]!.name, size: formData.vaccineProofDocuments[stepId]!.size }
              : null)
            : undefined,
        }])
    ),
    // Document metadata only — File objects are not serializable
    documents: {
      listA:            docs.listA            ? { name: docs.listA.name,            size: docs.listA.size            } : null,
      listB:            docs.listB            ? { name: docs.listB.name,            size: docs.listB.size            } : null,
      listC:            docs.listC            ? { name: docs.listC.name,            size: docs.listC.size            } : null,
      nursingLicense:   docs.nursingLicense   ? { name: docs.nursingLicense.name,   size: docs.nursingLicense.size   } : null,
      cprCertification: docs.cprCertification ? { name: docs.cprCertification.name, size: docs.cprCertification.size } : null,
    },
  };
}

// ── API calls ─────────────────────────────────────────────────────────────────

export async function submitOnboardingApplication(
  formData: OnboardingFormData,
): Promise<SubmitOnboardingResult> {
  const url = `${getApiBase()}/api/submit-onboarding`;

  let res: Response;
  try {
    res = await fetch(url, {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(buildPayload(formData)),
    });
  } catch {
    throw new ApiNetworkError();
  }

  let body: unknown;
  try {
    body = await res.json();
  } catch {
    throw new ApiError('Server returned an unexpected response.', res.status);
  }

  if (res.status === 422) {
    const payload = body as { issues?: ApiValidationIssue[] };
    throw new ApiValidationError(payload.issues ?? []);
  }

  if (!res.ok) {
    const payload = body as { error?: string };
    throw new ApiError(
      payload.error ?? 'Something went wrong. Please try again.',
      res.status,
    );
  }

  const payload = body as { applicationId?: string; submittedAt?: string };
  if (!payload.applicationId || !payload.submittedAt) {
    throw new ApiError('Server returned an incomplete response.', res.status);
  }

  return { applicationId: payload.applicationId, submittedAt: payload.submittedAt };
}

export async function uploadDocument(file: File): Promise<UploadResult> {
  const url = `${getApiBase()}/api/uploads`;
  const body = new FormData();
  body.append('file', file);

  let res: Response;
  try {
    res = await fetch(url, { method: 'POST', body });
  } catch {
    throw new ApiNetworkError();
  }

  let json: unknown;
  try {
    json = await res.json();
  } catch {
    throw new ApiError('Server returned an unexpected response.', res.status);
  }

  if (!res.ok) {
    const payload = json as { error?: string };
    throw new ApiError(
      payload.error ?? 'Upload failed. Please try again.',
      res.status,
    );
  }

  const payload = json as { objectKey?: string; fileName?: string; fileSize?: number; uploadedAt?: string };
  if (!payload.objectKey || !payload.fileName || !payload.uploadedAt) {
    throw new ApiError('Server returned an incomplete upload response.', res.status);
  }

  return {
    objectKey: payload.objectKey,
    fileName: payload.fileName,
    fileSize: payload.fileSize ?? file.size,
    uploadedAt: payload.uploadedAt,
  };
}
