// I-9 (Rev. 08/01/23) AcroForm field definitions.
// Coordinates are in PDF points (pt): x/y measured from bottom-left of the page.
// Page height = 792 pt. Field names match the exact AcroForm field names in the PDF.
// Generated by scripts/discover-i9-fields.mjs against the official USCIS PDF.

export interface I9FieldDef {
  page: number;         // 1-indexed
  x: number;           // distance from left edge, pt
  y: number;           // distance from bottom edge, pt
  w: number;           // width, pt
  h: number;           // height, pt
  fieldName: string;   // exact AcroForm field name for pdf-lib filling
}

// ── Page dimensions ────────────────────────────────────────────────────────────
export const PDF_PAGE_WIDTH  = 612;   // letter, pt
export const PDF_PAGE_HEIGHT = 792;   // letter, pt

// ── Section 1 — Employee Information and Attestation (Page 1) ─────────────────
// All fields the employee fills in. Source of truth is React/D1 state;
// these coordinates drive both the overlay UI and the backend AcroForm fill.
export const I9_SECTION1 = {
  // ── Legal name ───────────────────────────────────────────────────────────────
  lastName:        { page: 1, x:  43, y: 605, w: 156, h: 15, fieldName: 'Last Name (Family Name)' },
  firstName:       { page: 1, x: 204, y: 605, w: 138, h: 15, fieldName: 'First Name Given Name' },
  middleInitial:   { page: 1, x: 348, y: 605, w:  65, h: 15, fieldName: 'Employee Middle Initial (if any)' },
  otherLastNames:  { page: 1, x: 420, y: 605, w: 156, h: 15, fieldName: 'Employee Other Last Names Used (if any)' },

  // ── Address ──────────────────────────────────────────────────────────────────
  address:         { page: 1, x:  42, y: 580, w: 186, h: 14, fieldName: 'Address Street Number and Name' },
  aptNumber:       { page: 1, x: 234, y: 580, w:  66, h: 14, fieldName: 'Apt Number (if any)' },
  city:            { page: 1, x: 306, y: 580, w: 149, h: 14, fieldName: 'City or Town' },
  state:           { page: 1, x: 461, y: 580, w:  41, h: 14, fieldName: 'State' },
  zip:             { page: 1, x: 510, y: 580, w:  65, h: 14, fieldName: 'ZIP Code' },

  // ── Identity ─────────────────────────────────────────────────────────────────
  dateOfBirth:     { page: 1, x:  42, y: 554, w:  99, h: 14, fieldName: 'Date of Birth mmddyyyy' },
  ssn:             { page: 1, x: 150, y: 553, w: 105, h: 14, fieldName: 'US Social Security Number' },
  email:           { page: 1, x: 264, y: 554, w: 186, h: 14, fieldName: 'Employees E-mail Address' },
  phone:           { page: 1, x: 456, y: 553, w: 119, h: 14, fieldName: 'Telephone Number' },

  // ── Citizenship status checkboxes (one of CB_1–CB_4) ─────────────────────────
  // CB_1 = US Citizen, CB_2 = Noncitizen National, CB_3 = LPR, CB_4 = Alien Auth.
  cb_citizen:      { page: 1, x: 182, y: 523, w:   9, h:  9, fieldName: 'CB_1' },
  cb_national:     { page: 1, x: 182, y: 511, w:   9, h:  9, fieldName: 'CB_2' },
  cb_lpr:          { page: 1, x: 182, y: 499, w:   9, h:  9, fieldName: 'CB_3' },
  cb_alien:        { page: 1, x: 182, y: 487, w:   9, h:  9, fieldName: 'CB_4' },

  // ── Conditional: Lawful Permanent Resident ────────────────────────────────────
  lprANumber:      { page: 1, x: 391, y: 498, w: 185, h: 11, fieldName: '3 A lawful permanent resident Enter USCIS or ANumber' },

  // ── Conditional: Alien Authorized to Work ─────────────────────────────────────
  alienExpDate:    { page: 1, x: 390, y: 484, w:  59, h: 13, fieldName: 'Exp Date mmddyyyy' },
  alienANumber:    { page: 1, x: 181, y: 444, w:  83, h: 11, fieldName: 'USCIS ANumber' },
  i94Number:       { page: 1, x: 277, y: 444, w: 107, h: 11, fieldName: 'Form I94 Admission Number' },
  foreignPassport: { page: 1, x: 397, y: 444, w: 179, h: 11, fieldName: 'Foreign Passport Number and Country of IssuanceRow1' },

  // ── Signature ─────────────────────────────────────────────────────────────────
  signature:       { page: 1, x:  42, y: 421, w: 323, h: 13, fieldName: 'Signature of Employee' },
  signedDate:      { page: 1, x: 372, y: 421, w: 102, h: 13, fieldName: "Today's Date mmddyyy" },
} satisfies Record<string, I9FieldDef>;

// ── Section 2 — Employer Review (Page 1, bottom half; employer fills post-hire) ─
// These coordinates are shown as locked overlays in the employee's view.
// Employer fields at y < 420 on page 1, and additional content on page 4.
export const I9_SECTION1_BOUNDARY_Y = 420;   // fields below this y are employer territory

// ── Coordinate transform ───────────────────────────────────────────────────────
// Converts PDF field coordinates to CSS pixel position within a rendered canvas.
// PDF origin is bottom-left; CSS origin is top-left — so Y must be flipped.
export function pdfToScreen(
  field: I9FieldDef,
  scale: number,
  pageHeight = PDF_PAGE_HEIGHT,
): { left: number; top: number; width: number; height: number } {
  return {
    left:   field.x * scale,
    top:    (pageHeight - field.y - field.h) * scale,
    width:  field.w * scale,
    height: field.h * scale,
  };
}
